version: '3'

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "ttiKQ2JI9q"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "Zgtyz8mxX0O45zgRjd5q"
    ports:
      - "5432:5432"
  bot:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3000
